### ISSUE TITLE
Earnifi 502 FAIL

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/node-deploy#1]
**Describe the client's issue; include screenshots if necessary**
A clear and concise description of what the isse is.

**Essential Information**
Client name: Earnifi
Chain: ETH Mainnet
Endpoint in use: https://eth-mainnet.gateway.pokt.network/v1/lb/606cb4082a7941f2ff4f5169
Full request:
Reported result:
 
FAIL  src/api/fetchers.test.ts (26.751 s)

    bad response (status=502, headers={"server":"awselb/2.0","date":"Sun, 11 Apr 2021 19:54:27 GMT","content-type":"text/html","content-length":"122","connection":"close"}, body="<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n", requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x11f10378fc56277eedbc0c3309c457b0fd5c6dfd\",\"data\":\"0x73b2e80e000000000000000000000000bee17a0eec20ac4e0bc85f0862368ecd53801f13\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://eth-mainnet.gateway.pokt.network/v1/lb/606cb4082a7941f2ff4f5169", code=SERVER_ERROR, version=web/5.0.13)

      at Logger.Object.<anonymous>.Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.Object.<anonymous>.Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at node_modules/@ethersproject/web/src.ts/index.ts:251:24
      at step (node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (node_modules/@ethersproject/web/lib/index.js:5:58)

**Additional context**

**Comment by moatus** [comment]
Testing

**Comment by nymd** [comment]
Fixed with CPU issues.
