### ISSUE TITLE
Web3 Provider Error 400

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/node-deploy#10]
**Describe the client's issue; include screenshots if necessary**
Snowball is trying to connect via our Web3 Provider and is running into Error 400
![image](https://user-images.githubusercontent.com/15126267/115255730-8c3ddf80-a0fc-11eb-8b14-72a75e7c9081.png)

**Essential Information**
Client name: Snowball
Chain: ETH Mainnet
Endpoint in use: App ID: 6077e7bb7cbbfe002f0b9d31
Full request:
Reported result:
`{"code":400,"message":"ERROR:\nCodespace: pocketcore\nCode: 45\nMessage: \"the app could not be found in the world state\"\n"}

{"code":400,"message":"pocket node is currently syncing to the blockchain, cannot service in this state"}`

**Additional context**

**Comment by nymd** [comment]
Not sure if this was you or someone before you but please keep our database values sane 

![image](https://user-images.githubusercontent.com/16605170/115256397-0877f900-a0e4-11eb-982d-c8b23129b3ec.png)


"testing 123" is an awful name

**Comment by nymd** [comment]
```    "chains": [
        "0001",
        "0002",
        "0003",
        "0004",
        "0005",
        "0006",
        "0010",
        "0021",
        "0022",
        "0023",
        "0024",
        "0025",
        "0026",
        "0027"
    ],
    "jailed": false,
    "max_relays": "41750",
```
By staking all of those chains, the relays are split between each evenly. They have 41750 / 14 relays for each chain.

**Comment by nymd** [comment]
If I'm understanding the original post correctly, they are using the Web3 provider and not the Gateway? In that case, I need them in Discord as they are the first ones to do this and I have no idea what state it is in since I left.

**Comment by moatus** [comment]
I'm not sure who named this endpoint or how they got it.

I have asked them to use the Gateway for the initial integration. This will give us more insight and make things simple to begin with.
