### ISSUE TITLE
Batch of LB endpointed needed ASAP

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/node-deploy#14]
**Describe the client's issue; include screenshots if necessary**
Blep:
ETH Archival: 
https://eth-archival.gateway.pokt.network/v1/60818606af88c10031823756

ETH Mainnet:
https://eth-mainnet.gateway.pokt.network/v1/60818683af88c10031823758

Fuse (this endpoint needs to be added to their existing endpoint
https://fuse-mainnet.gateway.pokt.network/v1/60819061af88c1003182375f

Ferrum:
ETH Mainnet:
https://eth-mainnet.gateway.pokt.network/v1/608189d6af88c1003182375a
https://eth-mainnet.gateway.pokt.network/v1/6081a852af88c10031823764
https://eth-mainnet.gateway.pokt.network/v1/6081aaa0af88c10031823766
https://eth-mainnet.gateway.pokt.network/v1/6081ab24af88c10031823768
https://eth-mainnet.gateway.pokt.network/v1/6081abc7af88c1003182376a
https://eth-mainnet.gateway.pokt.network/v1/6081ac2aaf88c1003182376d
https://eth-mainnet.gateway.pokt.network/v1/6081ac92af88c1003182376f

**Comment by nymd** [comment]
Ferrum /v1/lb/6081ab29be01bc24b4fc2714

Blep mainnet /v1/lb/607f2e77be01bc24b4fc2713
Blep archival /v1/lb/6081d202be01bc24b4fc2715

Fuse done
