### ISSUE TITLE
Solana endpoint sending incomplete headers

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/node-deploy#2]
**Describe the client's issue; include screenshots if necessary**
The pokt.network response don't include the Solana custom header like Expect-CT, Report-To, NEL, CF-RAY, etc

**Essential Information**
Client name: Jarcodallo
Chain: Solana
Endpoint in use: https://solana-mainnet.gateway.pokt.network/v1/606f80cc7cbbfe002f0b9d18
Full request:
```
curl --location --request POST 'https://solana-api.projectserum.com' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cfduid=dde7541ec7452775e9f8d2df4a5d69e8b1618074050' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getAccountInfo",
    "params": [
      "2DWNkizveKLWnm93Roui3ueUnCp2dHVSW3Sf7Ex3yKpW",
      {
        "encoding": "base58"
      }
    ]
  }'
```
  
  I don't if you guys use Node.js, but maybe this can help too

```
var axios = require('axios');
var data = JSON.stringify({
  "jsonrpc": "2.0",
  "id": 1,
  "method": "getAccountInfo",
  "params": [
    "2DWNkizveKLWnm93Roui3ueUnCp2dHVSW3Sf7Ex3yKpW",
    {
      "encoding": "base58"
    }
  ]
});

var config = {
  method: 'post',
  url: 'https://solana-api.projectserum.com',
  headers: { 
    'Content-Type': 'application/json', 
    'Cookie': '__cfduid=dde7541ec7452775e9f8d2df4a5d69e8b1618074050'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

Reported result: 

**POKT endpoint response:**
![image](https://user-images.githubusercontent.com/15126267/114585924-2069fb80-9c52-11eb-964e-86eed67f174e.png)

**Native Solana endpoint Response:**
![image](https://user-images.githubusercontent.com/15126267/114586012-37a8e900-9c52-11eb-8145-d50d91887bc4.png)

**Additional context**
Jarcodallo is testing out our Solana endpoint. It sounds like they are an easy stage projects, so they are open to testing things our with Pocket.

**Comment by nymd** [comment]
Excellent report, no idea on the issue as no other blockchain we've dealt with expects headers back and forth.

**Comment by nymd** [comment]
```    "address": "586c774d7fb764b04b25861e25de122a6e66d6a1",
    "chains": [
        "0001",
        "0003",
        "0004",
        "0005",
        "0006",
        "0021"
    ],
    "jailed": false,
    "public_key": "8e050a3ba79364880b668fbed82207ff00f0d5241356c561507a933fef084508",
    "service_url": "https://pkt-0c4gs1baue-mainnet.off-chaindata.com:8081",
```

Whoever this is, is serving Solana incorrectly. This is not the cause of the issue, just an unrelated note.

**Comment by nymd** [comment]
1. Those appear to all be CloudFlare headers -- which is kind of an odd request as essential since they aren't returned by the blockchain node itself. What if a Pocket node runner is running a Solana node without Cloudflare?  There would be no headers.

2. If this is a still a desired thing, we need to open an issue against Pocket-JS to support returning headers.

**Comment by nymd** [comment]
Solana says headers removed is fine.
