### ISSUE TITLE
Fix Fuse's Grafana

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/node-deploy#8]
**Describe the client's issue; include screenshots if necessary**
I've checked the applicationpublickey and it matched the one I have in the Dashboard. I'm not sure if there are stakes I should be tracking, but the Fuse dashboard is not showing the right traffic.

It's important I be able to know there traffic so we can continue discussions.

Grafana link: https://grafana-mon.mainnet.pokt.network/d/a_-r2MlMz/fuse-network-gateway?orgId=1

**Essential Information**
Client name: Fuse
Chain: Fuse
Endpoint in use: https://fuse-mainnet.gateway.pokt.network/v1/605cd9f4e1261e00308bfb26
Full request:
Reported result:

**Comment by nymd** [comment]
Nothing is wrong with it.

https://grafana-mon.mainnet.pokt.network/d/a_-r2MlMz/fuse-network-gateway?orgId=1&from=now-3h&to=now

That is me hitting with Fuse's endpoint
https://fuse-mainnet.gateway.pokt.network/v1/605cd9f4e1261e00308bfb26

or

https://fuse-mainnet.gateway.pokt.network/v1/lb/6075e9510e2a131ca026e10d

**Comment by nymd** [comment]
Percentage of the requests served within a certain time (ms)
  50%    152
  66%    168
  75%    174
  80%    178
  90%    192
  95%    198
  98%    209
  99%    261
 100%    261 (longest request)


fast too

**Comment by moatus** [comment]
Their Grafana shows only 4216 request in the past 7 days (most of those are from the past few hours). They have done tests with 30k relays and they are not shoing up for some reason. I'm just trying to reconcile what why they we are not seeing the traffic they say are sending.
![image](https://user-images.githubusercontent.com/15126267/115026731-d6228d80-9e90-11eb-941e-c15cb639fdcd.png)

**Comment by nymd** [comment]
https://grafana-mon.mainnet.pokt.network/d/a_-r2MlMz/fuse-network-gateway?orgId=1&from=now-12h&to=now

These relays past 12 hours are not me. They are using it. I can't explain past that.
